SELECT 
    o.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(o.AMOUNT * p.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER AS o
JOIN FOOD_PRODUCT AS p
    ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN DATE '2022-05-01' AND DATE '2022-05-31'
GROUP BY o.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, o.PRODUCT_ID ASC;