WITH base AS (
  SELECT CAR_ID, START_DATE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE START_DATE >= '2022-08-01'
    AND START_DATE <  '2022-11-01'
),

eligible AS (
  SELECT CAR_ID
  FROM base
  GROUP BY CAR_ID
  HAVING COUNT(*) >= 5
)

SELECT
  MONTH(b.START_DATE) AS MONTH,
  b.CAR_ID,
  COUNT(*) AS RECORDS
FROM base b
JOIN eligible e USING (CAR_ID)
GROUP BY MONTH(b.START_DATE), b.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;