# SELECT *
# FROM ITEM_INFO i1
# LEFT JOIN ITEM_TREE t
#     ON i1.ITEM_ID = t.PARENT_ITEM_ID
# LEFT JOIN ITEM_INFO i2
#     ON t.ITEM_ID = i2.ITEM_ID

SELECT t.ITEM_ID, i2.ITEM_NAME, i2.RARITY
FROM ITEM_INFO i1
LEFT JOIN ITEM_TREE t
    ON i1.ITEM_ID = t.PARENT_ITEM_ID
LEFT JOIN ITEM_INFO i2
    ON t.ITEM_ID = i2.ITEM_ID
WHERE i1.RARITY = 'RARE' AND  i2.ITEM_ID IS NOT NULL
ORDER BY t.ITEM_ID DESC